kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: webhook-route
spec:
  parentRefs:
  - name: internal-https-gateway
  rules:
  - backendRefs:
    - name: webhook-backend-svc
      port: 8080